inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable


Gemspec/RequiredRubyVersion:
  Exclude:
    - 'feedjira.gemspec'

# Offense count: 3
# Configuration parameters: IgnoredMethods.
Metrics/AbcSize:
  Max: 24

# Offense count: 33
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 235

# Offense count: 7
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods.
Metrics/MethodLength:
  Max: 25

Layout/LineLength:
  Exclude:
    - 'spec/**/*.rb'

Style/AsciiComments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
