name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu]
        ruby: [2.5, 2.6, 2.7, head, jruby]
        handler: [nokogiri, ox, oga]
        exclude:
          - { ruby: jruby, handler: ox }

    name: >-
      ${{matrix.os}}-ruby${{matrix.ruby}}-${{matrix.handler}}
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.ruby == 'head' || matrix.ruby == 'jruby'}}
    env:
      HANDLER: ${{matrix.handler}}

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up ruby and bundle
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true

      - name: Run rake
        run: |
          bundle exec rake
